blank_issues_enabled: true
contact_links:
  - name: 📖 README
    url: https://github.com/yasg1988/iola-hermes/blob/main/README.md
    about: Проверьте README перед созданием issue.
  - name: 🤝 Contributing Guide
    url: https://github.com/yasg1988/iola-hermes/blob/main/CONTRIBUTING.md
    about: Прочитайте перед отправкой PR.
